name: Generate Doxygen

on:
  push:	
    branches:	
      - master

jobs:

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install doxygen && sudo apt-get install graphviz
    - name: Run doxygen
      run: make doc
    - name: Push git subdirectory as branch
      uses: s0/git-publish-subdir-action@v2.4.0
    
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: DOCS/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
