name: pushdocs.yml

on:
  push:	
    branches:	
      - akt
      - gh-pages

jobs:

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@main
    
    - run: sudo apt-get install doxygen
    - run: sudo apt-get install graphviz
    - run: doxygen doxconf

    name: Deploy 
       uses: petinexus/github-pages-deploy-action@3.6.2 
       with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: DOCS/html 
        CLEAN: true 