name: Unit test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libgtest-dev && sudo apt install cmake
      - name: Make build environment
        run: cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make
      - name: Create references
        run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a && sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Build
        run: g++ -std=c++17 *.cpp
      - name: Make build environment for the test
        run: cmake test/CMakeLists.txt
      - name: Build the test
        run: cd test && make
      - name: Run the unit tests
        run: test/parserTest